[package]
name = "gb-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.0.2"
clap = { version = "4.2.1", features = ["derive"] }
paste = "1.0.12"
